name: rpchat
main: net.gamerservices.rpchat.rpchat
version: 0.11
depend: [Vault,Essentials,Towny]
website: http://www.fallofanempire.com
author: Mixxit
database: true
description: >
             Basic localised chat functionality.
             This plugin allows a player to chat locally
commands:
  setelection:
    aliases: [setel]
    description: Sets an election type
    usage: |
           /<command> [name] [type]
           Example: /<command> name type
  setlanguage:
    aliases: [slang]
    description: Sets your current language
    usage: |
           /<command> [language]
           Example: /<command> common
  race:
    aliases: [setrace]
    description: Sets your current race
    usage: |
           /<command> [race]
           Example: /<command> Human
  promote:
    aliases: []
    description: Adds user to inviteonly group
    usage: |
           /<command> [onlinename]
           Example: /<command> Mixxit
  overlevel:
    aliases: []
    description: gets players overlevel
    usage: |
           /<command>
           Example: /<command> 
  reloadquests:
    aliases: []
    description: reloads quests
    usage: |
           /<command>
           Example: /<command> 
  demote:
    aliases: []
    description: Removes user to inviteonly group
    usage: |
           /<command> [onlinename]
           Example: /<command> Mixxit
  infection:
    aliases: [inf]
    description: Checks your infection status
    usage: |
           /<command> []
           Example: /<command> 
  random:
    aliases: [rand]
    description: Rolls a dice
    usage: |
           /<command> [sides]
           Example: /<command> 6
  gender:
    aliases: [setgender]
    description: Sets your current gender
    usage: |
           /<command> [race]
           Example: /<command> male
  reset:
    aliases: [resetspec]
    description: Resets a specialisation level
    usage: |
           /<command> [spectype]
           Example: /<command> natural 
  defaultchannel:
    aliases: [ch,setfocus]
    description: Sets your default chat channel
    usage: |
           /<command> [channel]
           Example: /<command> local
  local:
    aliases: [l]
    description: Speaks locally
    usage: |
           /<command> [msg]
           Example: /<command> Hello, people near me!
  emote:
    aliases: [e]
    description: Emotes locally
    usage: |
           /<command> [msg]
           Example: /<command> stops to examine the ground           
  alliancechat:
    aliases: [ac]
    description: Speaks to your alliance
    usage: |
           /<command> [msg]
           Example: /<command> Hello, alliance!     
  nationchat:
    aliases: [nc]
    description: Speaks to the nation
    usage: |
           /<command> [msg]
           Example: /<command> Hello, nation!   
  groupchat:
    aliases: [g]
    description: Adventure group chat
    usage: |
           /<command> [cmd]
           Example: /<command>   
  group:
    aliases: [gr]
    description: Adventure group commands
    usage: |
           /<command> [msg]
           Example: /<command> Hello, group!   
  townchat:
    aliases: [tc]
    description: Speaks to the town
    usage: |
           /<command> [msg]
           Example: /<command> Hello, town!        
  racechat:
    aliases: [rc]
    description: Speaks to your race
    usage: |
           /<command> [msg]
           Example: /<command> Hello, fellow species!
  name:
    aliases: [nick]
    description: Sets your name
    usage: |
           /<command> [newname]
           Example: /<command> Deborah
  lastname:
    aliases: [lastname]
    description: Sets your lastname
    usage: |
           /<command> [newlastname]
           Example: /<command> Smith
  findname:
    aliases: [find]
    description: Finds a players minecraft name
    usage: |
           /<command> [displayname]
           Example: /<command> Deborah
  getstats:
    aliases: [stats]
    description: Gets your player stats
    usage: |
           /<command>
           Example: /<command>
  meditate:
    aliases: [med]
    description: Meditates, increasing your power
    usage: |
           /<command>
           Example: /<command>

  alliance:
    aliases: [all]
    description: Accesses the King Alliance command
    usage: |
           /<command>
           Example: /<command>
  title:
    aliases: [settitle]
    description: Sets a title for you or someone else
    usage: |
           /<command>
           Example: /<command> [mcaccountname] [title]
  capital:
    aliases: [cap]
    description: Teleports you to your capital
    usage: |
           /<command>
           Example: /<command>
  who:
    aliases: [list]
    description: Lists people in your area
    usage: |
           /<command> [racename/playername]
           Example: /<command> 