name: rpchat
main: net.gamerservices.rpchat.rpchat
version: 0.08
website: http://www.fallofanempire.com
author: Mixxit
database: true
description: >
             Basic localised chat functionality.
             This plugin allows a player to chat locally
commands:
  race:
    aliases: [setrace]
    description: Sets your current race
    usage: |
           /<command> [race]
           Example: /<command> Human
  metatron:
    aliases: [metatron]
    description: Summon the metatron
    usage: |
           /<command> [message]
           Example: /<command> my message
  defaultchannel:
    aliases: [ch]
    description: Sets your default chat channel
    usage: |
           /<command> [channel]
           Example: /<command> local
           Valid Channel names: local,global,race,town,ooc 
  local:
    aliases: [l]
    description: Speaks locally
    usage: |
           /<command> [msg]
           Example: /<command> Hello, people near me!
  ooc:
    aliases: [oo,oc]
    description: Speaks out of character (global to that world)
    usage: |
           /<command> [msg]
           Example: /<command> Hello, people in this world!
  townchat:
    aliases: [tc]
    description: Speaks to your town
    usage: |
           /<command> [msg]
           Example: /<command> Hello, townies!
  alliancechat:
    aliases: [ac]
    description: Speaks to your alliance
    usage: |
           /<command> [msg]
           Example: /<command> Hello, alliance!           
  racechat:
    aliases: [rc]
    description: Speaks to your race
    usage: |
           /<command> [msg]
           Example: /<command> Hello, fellow species!
  name:
    aliases: [nick]
    description: Sets your name
    usage: |
           /<command> [newname]
           Example: /<command> Deborah
           
  lastname:
    aliases: [lastname]
    description: Sets your lastname
    usage: |
           /<command> [newlastname]
           Example: /<command> Smith
  findname:
    aliases: [find]
    description: Finds a players minecraft name
    usage: |
           /<command> [displayname]
           Example: /<command> Deborah
  vote:
    aliases: [votebymcname]
    description: Votes by a minecraft name - to find a minecraft name use /findname Fakenamehere
    usage: |
           /<command> [minecraftname]
           Example: /<command> Deborahz
  doelection:
    aliases: [doelection]
    description: Sets yourself for election
    usage: |
           /<command>
           Example: /<command>
  title:
    aliases: [settitle]
    description: Sets a title for you or someone else
    usage: |
           /<command>
           Example: /<command> [mcaccountname] [title]
  setcapital:
    aliases: [scap]
    description: Sets the capital location to your position
    usage: |
           /<command>
           Example: /<command>
  capital:
    aliases: [cap]
    description: Teleports you to your capital
    usage: |
           /<command>
           Example: /<command>
  global:
    aliases: [g]
    description: Speaks out of character (global to the whole server)
    usage: |
           /<command> [msg]
           Example: /<command> Hello, people in this server!